//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_Store_Downloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MS_Store_Downloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap animated_loading {
            get {
                object obj = ResourceManager.GetObject("animated_loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Envelope xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.w3.org/2003/05/soap-envelope&quot;&gt;
        ///	&lt;Header&gt;
        ///		&lt;Action d3p1:mustUnderstand=&quot;1&quot; xmlns:d3p1=&quot;http://www.w3.org/2003/05/soap-envelope&quot; xmlns=&quot;http://www.w3.org/2005/08/addressing&quot;&gt;http://www.microsoft.com/SoftwareDistribution/Server/ClientWebService/GetCookie&lt;/Action&gt;
        ///		&lt;MessageID xmlns=&quot;http://www.w3.org/2005/08/addressing&quot;&gt;urn:uuid:b9b43757-2247-4d7b-ae8f-a71ba8a22386&lt;/MessageID&gt;
        ///		&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cookie {
            get {
                return ResourceManager.GetString("cookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope
        ///	xmlns:a=&quot;http://www.w3.org/2005/08/addressing&quot;
        ///	xmlns:s=&quot;http://www.w3.org/2003/05/soap-envelope&quot;&gt;
        ///	&lt;s:Header&gt;
        ///		&lt;a:Action s:mustUnderstand=&quot;1&quot;&gt;http://www.microsoft.com/SoftwareDistribution/Server/ClientWebService/GetExtendedUpdateInfo2&lt;/a:Action&gt;
        ///		&lt;a:MessageID&gt;urn:uuid:2cc99c2e-3b3e-4fb1-9e31-0cd30e6f43a0&lt;/a:MessageID&gt;
        ///		&lt;a:To s:mustUnderstand=&quot;1&quot;&gt;https://fe3.delivery.mp.microsoft.com/ClientWebService/client.asmx/secured&lt;/a:To&gt;
        ///		&lt;o:Security s:mustUnderstand=&quot;1&quot;
        ///			xmlns:o=&quot;http://doc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope
        ///	xmlns:a=&quot;http://www.w3.org/2005/08/addressing&quot;
        ///	xmlns:s=&quot;http://www.w3.org/2003/05/soap-envelope&quot;&gt;
        ///	&lt;s:Header&gt;
        ///		&lt;a:Action s:mustUnderstand=&quot;1&quot;&gt;http://www.microsoft.com/SoftwareDistribution/Server/ClientWebService/SyncUpdates&lt;/a:Action&gt;
        ///		&lt;a:MessageID&gt;urn:uuid:175df68c-4b91-41ee-b70b-f2208c65438e&lt;/a:MessageID&gt;
        ///		&lt;a:To s:mustUnderstand=&quot;1&quot;&gt;https://fe3.delivery.mp.microsoft.com/ClientWebService/client.asmx&lt;/a:To&gt;
        ///		&lt;o:Security s:mustUnderstand=&quot;1&quot;
        ///			xmlns:o=&quot;http://docs.oasis-open.org/ws [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wu {
            get {
                return ResourceManager.GetString("wu", resourceCulture);
            }
        }
    }
}
